# Generated by Django 4.2 on 2023-04-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_friend_fuelprice_transporttype_userbudget_routes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routes',
            name='waypoints',
        ),
        migrations.AddField(
            model_name='routes',
            name='destination',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='routes',
            name='origin',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='userbudget',
            name='fuelType',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
