# Generated by Django 4.2 on 2023-04-29 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_remove_routes_waypoints_routes_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='userbudget',
            name='mpg',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=16),
        ),
        migrations.AlterField(
            model_name='fuelprice',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.CreateModel(
            name='carShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('routeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeapp.routes')),
            ],
        ),
    ]
