# Generated by Django 4.2 on 2023-05-15 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_alter_routes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbudget',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userbudget',
            name='fuelType',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='userbudget',
            name='mpg',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
