# Generated by Django 4.2 on 2023-05-17 12:43

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 17, 13, 43, 54, 675432)),
        ),
        migrations.AlterField(
            model_name='routes',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='routes',
            name='emissions',
            field=models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
