# Generated by Django 4.2 on 2023-05-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_routes_distance_alter_message_date_alter_routes_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
